# Generated by Django 4.2.2 on 2023-06-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_id_alter_order_id_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='id',
            new_name='iid',
        ),
    ]
