# Generated by Django 4.2.2 on 2023-06-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_id_payment_iid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='iid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
