# Generated by Django 4.2.2 on 2023-06-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='addresses',
        ),
    ]
